alerts:
- rule: DEPLOYMENT_FAILED
- rule: DOMAIN_FAILED
features:
- buildpack-stack=ubuntu-22
ingress: {}
name: stop-bot
region: nyc
workers:
- environment_slug: go
  envs:
  - key: STOP_BOT_TOKEN
    scope: RUN_AND_BUILD_TIME
    type: SECRET
    value: EV[1:H0CS4rZAacPgu4hnaxcH6Ig4MYmeVnrE:ou4kSvVuAwrzG56fu4vwhVrW5UnljPhblxnmjVfbUzDU8yGwknUGk/zIWTvBS5pLdKCzWVdIKLbq3WIohC9d3ZP3Pbjtk85LpjYbJl43x375hjL3Id0yJw==]
  - key: STOP_BOT_APP_ID
    scope: RUN_AND_BUILD_TIME
    type: SECRET
    value: EV[1:6B0twRHHq/d0FDOggLw9RSFtkKcrs2mj:rP7bYw34BDtSoGveGGC3MK/BGSMHkjWQogshjLsxlH+kFcw=]
  - key: STOP_BOT_PUBLIC_KEY
    scope: RUN_AND_BUILD_TIME
    type: SECRET
    value: EV[1:cgwxO3nUnaoawlnwRw+zJlffRORLXNr2:RoDnyhXsGeqMqohHaksXxGi+vic10iAFUBwkrMUUbXWyecVJuwACEg+kATPAuXLvhIjgc1J/z/9T2ygdFZuyAR3y4mO3H+aW4lz5bxsrcFc=]
  - key: STOP_BOT_STOPPED_ROLE_ID
    scope: RUN_AND_BUILD_TIME
    type: SECRET
    value: EV[1:6qtOIwrQ1Bl+Qzs7lT/XD5ZW0v4Yb6fY:cU3xu0SVYqkRKn2qWDZS8vTb4rtHXbQKSPYawypiI7ve/pg=]
  - key: GUILD_ID
    scope: RUN_AND_BUILD_TIME
    type: SECRET
    value: EV[1:2Q9KRiBQ4JtJUDPOmdpZvoBPjqFqPFvo:wdkhf3pN6PdwUXaLbM92J0YDsQGo0tUTUzHZ4Gux+aXRjQ==]
  github:
    branch: main
    deploy_on_push: true
    repo: tmaffia/discord-bots
  instance_count: 1
  instance_size_slug: basic-xxs
  name: discord-bots
  run_command: bin/bots
  source_dir: /
