alerts:
- rule: DEPLOYMENT_FAILED
- rule: DOMAIN_FAILED
features:
- buildpack-stack=ubuntu-22
ingress: {}
name: discord-bots
region: nyc
workers:
- dockerfile_path: Dockerfile
  envs:
  - key: TYRANT_TOKEN
    scope: RUN_AND_BUILD_TIME
    type: SECRET
    value: EV[1:vXx4Ajyh1vvqLaTr5brMO5d3XmhXaAed:xZ0LVnWMS3n8ktQFEpX/SpioVzp5btathtqoPRiy6vxuqeTiPC4tQ2eriGfQ2QOo0b8XJUAGuehDaQEkBYvI4V6Yti9QKQygs7HmEjmUCbxNIxKR1vuNVg==]
  - key: TYRANT_APP_ID
    scope: RUN_AND_BUILD_TIME
    type: SECRET
    value: EV[1:kYGqaApLPY+a1pVp5Ju+ghJxxiQEDEqZ:ZqNMtYXcGb++gDFkzVlbn6ajEx2sSWhsnEad5HGt46u0nZQ=]
  - key: TYRANT_PUBLIC_KEY
    scope: RUN_AND_BUILD_TIME
    type: SECRET
    value: EV[1:VWPAiQJPhPgL7d8L0k+oPAbF7yjNpjOT:BN1W9vDGjgL1sPiWxRZl4S1bB8sCGJpobLUaw0QlKFLIGjgFZ5GmyZm0rLJI37iEIu2b4HBvQMaQnh7WCUwWiWwxEWb8csKOIdtSb7+rf0A=]
  - key: TYRANT_STOPPED_ROLE_ID
    scope: RUN_AND_BUILD_TIME
    type: SECRET
    value: EV[1:bC8jWhcJIy8tLmyHgjn/NiU55BAqAz+x:vtOxuwVOSZAE+YW764qRO4BjrsJJ9+a1942r7IhF0lSsiNs=]
  - key: GUILD_ID
    scope: RUN_AND_BUILD_TIME
    type: SECRET
    value: EV[1:rJw8mx39cuGWQij1TUj0X18nbuyauB8X:opo5ala6x4xEVeHvdFNsBz+QnMlISdF89km+jM+jD790BQ==]
  github:
    branch: main
    deploy_on_push: true
    repo: tmaffia/tyrant
  instance_count: 1
  instance_size_slug: basic-xxs
  name: tyrant
  source_dir: /
