alerts:
- rule: DEPLOYMENT_FAILED
- rule: DOMAIN_FAILED
features:
- buildpack-stack=ubuntu-22
ingress: {}
name: stop-bot
region: nyc
workers:
- environment_slug: go
  envs:
  - key: STOP_BOT_TOKEN
    scope: RUN_AND_BUILD_TIME
    type: SECRET
    value: EV[1:gVv6dqwANoYlBcdY8E4ZGXYA9vz86lnA:XY3mhJbm/IzMxH8SRdol2aZgMX2OJY9g9HXB9GPOcM8YrMyDiX3SBYy6Q+mdDFUJj0OT7Jm2i2ScRofDtAkPLV0fsOT4fFgsN+T3/TszN7NF1B4Q7jTjpg==]
  - key: STOP_BOT_PUBLIC_KEY
    scope: RUN_AND_BUILD_TIME
    type: SECRET
    value: EV[1:5eQLpAEhcScRXtRuK/skIQCMzZ7FGluJ:1mN7SMCjZ1lgpSWAQcwpxyub4Xiqi9gCcDxYuep2vt4gTEtnB4xz+nTGaO6vK9HH0eB6DB0bD6Wz55Q6HXYOzYWHqeb4zsb6wdIE+5dnNSk=]
  - key: STOP_BOT_APP_ID
    scope: RUN_AND_BUILD_TIME
    type: SECRET
    value: EV[1:mU6SKzhO71lusReJkstUqu2hzRq98+3g:b+lEA72SardOZdqBc5fkTKqguNz1C+HOFRmyOiRJjB+y5p0=]
  github:
    branch: main
    deploy_on_push: true
    repo: tmaffia/discord-bots
  instance_count: 1
  instance_size_slug: basic-xxs
  name: discord-bots
  run_command: bin/bots
  source_dir: /
